### PR TITLE
Final Version of the Budget-App - RoR Capstone Project

### PR DESCRIPTION
**Pull request by Luffytaro22**
> # Budget-App RoR Capstone project 🔥 
> * Use of `devise` and `CanCanCan` gems to `authenticate` and `authorize` the users.
> * Created `users`, `groups`, `purchases`, and `groups purchases` tables `migrations` based on the `Entity Relationship Diagram`.
> * Created all the necessary `models` and `controllers` for the `users`, `groups`, and `purchases` with their respective validations.
> * Created all the `devise` views (login and register), the `groups index (/groups)` page with all the `categories`, the `groups new (/groups/new)` page to create a new category, the `purchases index (/groups/:group_id/purchases)` page to display all the `transactions` for a category, and the `purchases new (/groups/:group_id/purchases/new)` page to create a new transaction for a specific category (all of them as .erb files).
> * Created `unit` and `integrations` `tests` with `RSpec`, `Capybara`, and `Factory Bot`, for the `models`, `requests`, and `views`. All of them test the correct functionality of the entire application.
> * The application is successfully deployed and accessible through this link: https://budget-app-8wpl.onrender.com/
> * [This is the video presentation of the project](https://drive.google.com/file/d/1sYThPupwEd6hsfnNaWhBPLvemaGte41G/view?usp=sharing)

# ⭐To the code reviewer 👨‍💻

💝 I really thank 🙇‍♂️ you, dear code reviewer 👨‍🎨 for dedicating your precious 🥇 time ⌚ to check the PR 🧾 .

I kindly ask 🙏 dear code reviewer 🤵 that if there is any kind of issue 🦯 in this project, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

### CODE REVIEW

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi @Luffytaro22 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 

You have submitted a project, that does not follow the right gitflow. Features branches should push the `dev` branch. 
- Also, kindly fix the failed linters

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by joel-kalema — COMMENTED** [review]
Hi team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

pirates-of-the-caribbean-johnny-depp


- [ ] You have submitted a project that has linters that do not pass, make sure you solve them and then ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Reem-lab** [comment]
Hello @Luffytaro22 could you check your slack?

**Review by rloterh — COMMENTED** [review]
Hi Manuel, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the Pull Request for this activity should flow **from feature into development**, . Kindly use the correct gitflow, like you've done in https://github.com/Luffytaro22/Budget-app/pull/8.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
